nuxt.config.ts

- close #21 
- #21 
- titleの岡山を京都に修正

update : titleの岡山を京都に修正

---

CONTRIBUTORS.md
pages/about.vue

update : 現段階での京都版開発者を追加

---

components/cards/TestedNumberCard.vue
pages/index.vue

- close #30 
- close #28 
- #30 
- #28 
- 検査実施数のコメントを削除
- 最新のお知らせに掲示するデータがないので一旦非表示

検査実施数のコメントを削除&最新のお知らせを一旦非表示

---

README.md
components/NoScript.vue
layouts/default.vue
layouts/print.vue
nuxt.config.ts

- close #33 
- close #34 
- #33 
- #34 
- OGP画像の変更
-  Issue URLの変更
- 東京都と岡山県表記を京都府に変更

update : OGP画像、IssueURL、東京都と岡山県表記の変更

---

nuxt.config.ts

- close #29
- Google Analytics の ID を京都府版に変更した

Google Analytics の ID を京都府版に変更

---

nuxt.config.ts
pages/about.vue

- close #41 
- close #42
- 連絡先の変更
- OGP リンクを変更

連絡先の変更および OGP リンクの差し替え

---

layouts/default.vue
layouts/print.vue

- close #47
- default.vue および print.vue のリンクを正式版のものに差し替えた

default.vue および print.vue のリンク差し替え

---

.github/workflows/deploy.yml

- #44
- deploy.yml を修正したうえで master へマージ

deploy.yml を京都府版に合うように設定

---

README.md

- #44
緊急事態により、私のアカウントのアクセストークンをこちらのリポジトリに割り当てました。
再度デプロイするためのトリガーを引くため、README.md を修正しました。

【緊急】トークンの発行

---

FORKED_SITES.md

- #44
- トリガー発動
- FORKED_SITES.md に、当チームの STOP COVID-19 を追加

【緊急】トリガー発動 ／ FORKED_SITES.md に、当チームの STOP COVID-19 を追加

---

CONTRIBUTING.md

- #77 
なし
リンクをhttps://dev-stop-covid19-kyoto.netlify.com/ に変更した
なし

開発用サイトのリンクが古いまま

---

.github/workflows/update-data.yml

手動でデータ更新できるように

---

CONTRIBUTORS.md

add : CONTRIBUTOR

---

CONTRIBUTORS.md
pages/about.vue

add : 開発者を追加

---

README.md
netlify.toml

- close #131
- netlify.toml に、https://stop-covid19-netlify.com/ から https://kyoto.stopcovid19.jp/ へリダイレクトする設定を追加

リダイレクトの設定を追加

---

.github/workflows/update-data.yml

add labels

---

.github/workflows/develop.yml
components/DataViewShare.vue
components/OpenDataLink.vue
components/cards/TestedNumberCard.vue
nuxt.config.ts
pages/worker.vue

- SSIA
- あと、一部「東京都」を書き換え忘れてたので書き換え

eslintとdevelop deploy

---

.github/workflows/update-data.yml

- #500
- 自動更新メールが届いていない際に、データを更新せずにそのままプルリク投げてもらうようにした

メールが届いてない？ファイルがない？しかたない、更新はナシだ。

---

.github/workflows/update-data.yml

- close #515 
- update-data.yml に workflow_dispatch を追加

workflow_dispatch を追加

---

components/DataTable.vue
components/cards/ConfirmedCasesAttributesCard.vue
components/cards/TestedNumberCard.vue
utils/formatTable.ts

- #545 
- #495
- 陽性者の属性に何例目か表示される機能を追加
- 文言を修正

陽性者の属性に何例目か表示される機能を追加、文言を修正

---

components/ConfirmedCasesDetailsTable.vue
utils/formatConfirmedCases.ts

- close #555
- 重症者・調整中の患者の状況を表示

重症者・調整中の患者の状況を表示

---

.github/workflows/deploy-data.yml

自動デプロイの条件を変更

---

.github/workflows/deploy-data.yml

- なし
- deploy-data実行時にgoogle analytics idを出力し、反映されるようにした

add echo google analytics id process

---

.github/workflows/deploy-data.yml

なし
- workflow dispatch を用いて deploy-data.yml を実行できるようにした

Added workflow dispatch on deploy-data.yml

---

.github/workflows/i18n_generator.yml

[Hotfix] Update i18n_generator.yml

---

.github/workflows/update-data.yml

[hotfix] Update update-data.yml

---

Dockerfile

- close #852 
- イメージ構築時に Python, make, g++ をインストールするように変更

ARM 環境下で Docker イメージ構築時にパッケージのビルドが行えるように変更

---

components/SideNavigation.vue

宇治田原町のリンクを更新

---

components/DataTable.vue
components/cards/ConfirmedCasesAttributesCard.vue
utils/formatTable.ts

欠番1件ありの注釈を追加

---

README.md

- close #1077 
- (非公式)を外した
- https://kyoto.stopcovid19.jp/about からサイトの説明を引用

README.mdの訂正

---

components/DataTable.vue

[Hotfix]欠番を3人に変更

---

components/SideNavigation.vue

[Hotfix] Fixed some links on SideNavigation.vue

---

components/DataTable.vue

[Hotfix] 欠番の数を増加

---

components/DataTable.vue

[Hotfix] Increased missing number

---

components/DataTable.vue

[Hotfix] 欠番を6人に変更

---

components/DataTable.vue

[Hotfix] 欠番を13件に変更

---

components/SideNavigation.vue

- close #1398 
- リンク切れした自治体サイトのリンクを修正

自治体サイトのリンク切れを修正

---

components/DataTable.vue

[Hotfix]欠番を15件に変更

---

.github/workflows/update-data.yml

- close #1429 
- 9時と23時のデータ更新スケジュールを追加

データの自動更新スケジュールを追加

---

components/DataTable.vue

[Hotfix] 欠番を18件に変更

---

components/DataTable.vue

[Hotfix] 欠番の数を20件に変更

---

components/DataTable.vue

[Hotfix] 欠番を27件に変更

---

components/DataTable.vue

[Hotfix] 欠番を29件に変更

---

components/DataTable.vue

[Hotfix] 欠番を30件に変更

---

components/DataTable.vue

[Hotfix] 欠番を31件に変更

---

.github/workflows/deploy-data.yml

- Branch Protection Botの命名規則の変更に対応

[Hotfix] Branch Protection Botの命名規則の変更に対応

---

.github/workflows/deploy.yml

- deploy.ymlのBranch Protection Botの命名規則を修正

[Hotfix] deploy.ymlのBranch Protection Botの命名規則を修正

---

components/DataTable.vue

[Hotfix] 欠番を73件に変更

---

components/DataTable.vue

[Hotfix] 欠番を82件に変更

---

components/DataTable.vue

[Hotfix] 欠番を85件に変更

---

components/SideNavigation.vue

京田辺市のリンクを変更

---

components/DataTable.vue

[Hotfix] 欠番を86件に変更

---

components/DataTable.vue

[Hotfix] 欠番数を87件に変更

---

components/DataTable.vue

[Hotfix] 欠番件数を88件に変更

---

components/DataTable.vue

[Hotfix] 欠番を89件に変更

---

components/DataTable.vue

[Hotfix] 欠番件数を90件に変更

---

components/DataTable.vue

[Hotfix] 欠番件数を92件に変更

---

components/DataTable.vue

[Hotfix] 欠番件数を96件に変更

---

components/DataTable.vue

[Hotfix] 欠番の件数を100件に変更

---

components/DataTable.vue

[Hotfix] 欠番の件数を108件に変更

---

components/CardsKyoto.vue

陽性者の属性カードを無効化

---

components/SideNavigation.vue

サイドバーの宇治田原町のリンクを修正
